# SConscript
# vim: set ft=python:
#
# SConscript for building tests for charles.
#
# Eryn Wells <eryn@erynwells.me>

Import('env')
Import('gtest')
Import('charles_lib')

files = Split("""
""")

prog = env.Program('test_charles', [gtest, charles, files])
env.Alias('test', prog)
