# SConscript
# vim: set ft=python:
# Eryn Wells <eryn@erynwells.me>

Import('env')


test_env = env.Clone()
test_env.Append(CPPDEFINES='GTEST_USE_OWN_TR1_TUPLE')


subdirs = [
    # TODO: Put subdirectories here.
]

for d in subdirs:
    env.SConscript(env.Dir(d).File('SConscript'), {'env': test_env})


files = [
    'test_basics.cc',
    'test_charles.cc',
]

objs = []
for f in files:
    objs.append(env.Object(f))


prog = test_env.Program('test_charles', files, libs=[gtest, charles])
env.Alias('test', prog)
