# SConscript
# vim: set ft=python:
# Eryn Wells <eryn@erynwells.me>

Import('env')


subdirs = [
    # TODO: Put subdirectories here.
]

for d in subdirs:
    env.SConscript(env.Dir(d).File('SConscript'), {'env': env})


files = [
    'test_basics.cc',
    'test_charles.cc',
]

objs = []
for f in files:
    objs.append(env.Object(f))


prog = env.Program('test_charles', objs, LIBS=['gtest', 'charles'])
env.Alias('test', prog)
