# SConscript
# vim: set ft=python:
#
# SConscript for Google C++ Testing Framework.
#
# Eryn Wells <eryn@erynwells.me>

Import('env')

files = Glob('src/*.cc')

gtest_env = env.Clone()
gtest_env['CPPPATH'] = ['.', './include']
gtest_env.Append(CPPDEFINES=['GTEST_USE_OWN_TR1_TUPLE'])

gtest = gtest_env.Library('gtest', files)
env.Alias('gtest', gtest)
Return('gtest')
