# SConscript
# vim: set ft=python:
# Eryn Wells <eryn@erynwells.me>

Import('env')


files = [
    'parsers.cc',
    'object_parser.cc',
    'scalarMappingParser.cc',
    'sceneParser.cc',
]

objs = []
for f in files:
    objs.append(env.Object(f))

Return('objs')
