# SConscript
# vim: set ft=python:
# Eryn Wells <eryn@erynwells.me>

Import('env')

files = Split("""
    basics.c
    camera.c
    object.c
    scene.c
    texture.c
    writer_png.c
""")

lib = env.Library('charles', files)
prog = env.Program('charles', [lib, 'charles.c'])
env.Alias('charles', prog)

Return('lib')
