# SConscript
# vim: set ft=python:
# Eryn Wells <eryn@erynwells.me>

Import('env')


subdirs = [
    # TODO: Put subdirectories here.
]

for d in subdirs:
    env.SConscript(env.Dir(d).File('SConscript'), {'env': env})


files = [
    'basics.cc',
    'camera.cc',
    'light.cc',
    'material.cc',
    'object.cc',
    'object_sphere.cc',
    'object_plane.cc',
    'reader_yaml.cc',
    'scene.cc',
    'writer_png.cc',
]

objs = []
for f in files:
    objs.append(env.Object(f))

lib = env.Library('charles', files)
prog = env.Program('charles', ['charles.cc'], LIBS=[lib, 'png', 'yaml'])
env.Alias('charles', prog)

env.Default('charles')
